import Head from 'next/head'
import About from '../Components/About'
import styles from '@/styles/index.module.scss'
import HomePage from '../Components/Home'
import WelcomePage from '@/Components/WelcomePage'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePage/>
        <About/>
        <WelcomePage/>
      </main>
    </>
  )
}
