import Head from 'next/head'
import About from '@/Components/About'
import styles from '@/styles/index.module.scss'
import HomePage from '@/Components/Home'
import WelcomePage from '@/Components/WelcomePage'
import { useSelector } from 'react-redux'
export default function Index() {
  const userId=useSelector((state:{rootReducer:{storeData:{userId:string}}})=>state.rootReducer.storeData.userId);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {userId.length<=0?<><HomePage/>
        <About/></>:
        <WelcomePage/>}
      </main>
    </>
  )
}
